EMBEDDING_ENCODER_MODEL = "intfloat/multilingual-e5-large-instruct"
HASHTAG_TAGGER_MODEL = "HuggingFaceTB/SmolLM2-360M-Instruct"

PDF_CHUNK_SIZE = 1000
PDF_CHUNK_OVERLAP = 200

RAG_SEARCH_K = 10
RAG_SIMILARITY_THRESHOLD = 0.9